CREATE TABLE IF NOT EXISTS winners (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  menu TEXT NOT NULL,
  card_id INTEGER NOT NULL,
  card_name TEXT NOT NULL,
  description TEXT,
  image TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_winners_menu_created_at
ON winners(menu, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_winners_menu_card
ON winners(menu, card_id);

CREATE TABLE IF NOT EXISTS favorite_topics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL,
  label TEXT NOT NULL,
  country TEXT,
  icon TEXT,
  era INTEGER,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_favorite_topics_value
ON favorite_topics(value);

CREATE INDEX IF NOT EXISTS idx_favorite_topics_era
ON favorite_topics(era);

CREATE TABLE IF NOT EXISTS favorite_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id INTEGER NOT NULL,
  source_card_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  image TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (topic_id) REFERENCES favorite_topics(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_favorite_cards_topic_source_card
ON favorite_cards(topic_id, source_card_id);

CREATE INDEX IF NOT EXISTS idx_favorite_cards_topic_id
ON favorite_cards(topic_id);

-- BEGIN pick-your-favorite seed data
-- Seed data for the pick-your-favorite API tables.
INSERT INTO favorite_topics (value, label, country, icon, era)
VALUES
  ('boy-idol', '2020년대 K-POP 남자아이돌', 'kr', './assets/icons/boy-idol.svg', 2020),
  ('girl-idol', '2020년대 K-POP 여자아이돌', 'kr', './assets/icons/girl-idol.svg', 2020),
  ('2020-us-female-singer', '2020년대 미국 여자가수', 'us', './assets/icons/female-singer.svg', 2020),
  ('2020-us-male-singer', '2020년대 미국 남자가수', 'us', './assets/icons/male-singer.svg', 2020),
  ('2020-progressive-politician', '2020년대 진보정치인', 'kr', './assets/icons/progressive-politician.svg', 2020),
  ('2020-conservative-politician', '2020년대 한국보수정치인', 'kr', './assets/icons/conservative-politician.svg', 2020),
  ('2020-kbo-baseball-player', '2020년대 한국리그 야구선수', 'kr', './assets/icons/baseball-player.svg', 2020),
  ('2020-mlb-baseball-player', '2020년대 미국리그 야구선수', 'us', './assets/icons/baseball-player.svg', 2020),
  ('1990-male-singer', '1990년대 남자가수', 'kr', './assets/icons/male-singer.svg', 1990),
  ('1990-female-singer', '1990년대 여자가수', 'kr', './assets/icons/female-singer.svg', 1990),
  ('atashinchi-character', '아따맘마 캐릭터', NULL, './assets/icons/atashinchi-character.svg', NULL),
  ('rude-miss-young-ae', '막돼먹은 영애씨', 'kr', './assets/icons/rude-miss-young-ae.svg', NULL),
  ('pororo-character', '뽀로로 캐릭터', 'kr', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PororoCurrentOutfit.jpg', NULL)
ON CONFLICT(value) DO UPDATE SET
  label = excluded.label,
  country = excluded.country,
  icon = excluded.icon,
  era = excluded.era,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO favorite_cards (topic_id, source_card_id, name, description, image)
VALUES
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 1, 'BTS 뷔', '2020년대 K-POP 남자아이돌 후보', '2021030206031071070_2.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 2, 'BTS 진', '2020년대 K-POP 남자아이돌 후보', '2024103114483542528_1.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 3, '워너원 박지훈', '핑크머리가 잘 어울리는 남자 아이돌', 'SSI_20180406175623.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 4, 'BTS 정국', '97년생 가장 잘생긴 남자아이돌', 'BF.28795182.1.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 5, '한유진', '지창욱 닮았네', '한유진.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 6, '김지웅', '아디다스', '1d0964bb77d77845822cef230bdca625.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 7, 'ASTRO 차은우', '이동민', '17922a82efa53413b.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 8, '용복이', '원빈분위기', '604716469_17891244630399592_2100646603588067718_n.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 9, 'BTS 지민', 'BTS의 보컬과 퍼포먼스를 맡는 솔로 아티스트', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Jimin_on_the_way_to_SBS_Radio%2C_31_March_2023_%282%29.jpg/330px-Jimin_on_the_way_to_SBS_Radio%2C_31_March_2023_%282%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 10, 'BTS 슈가', 'BTS의 래퍼이자 Agust D로도 활동하는 프로듀서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Suga_for_Valentino_and_Marie_Claire_Korea_06.jpg/330px-Suga_for_Valentino_and_Marie_Claire_Korea_06.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 11, 'BTS RM', 'BTS의 리더이자 래퍼, 송라이터, 프로듀서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/RM_at_W_Korea_Love_Your_W%2C_November_2023.jpg/330px-RM_at_W_Korea_Love_Your_W%2C_November_2023.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 12, 'BTS 제이홉', 'BTS의 래퍼와 댄서를 맡는 솔로 아티스트', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/J-Hope_at_W_Korea_Breast_Cancer_Campaign%2C_15_October_2025.png/330px-J-Hope_at_W_Korea_Breast_Cancer_Campaign%2C_15_October_2025.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 13, 'EXO 백현', 'EXO와 EXO-CBX, SuperM으로 활동한 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/%ED%95%98%EC%96%80%EB%A8%B8%EB%A6%AC_%EB%B0%B1%ED%98%84_3.jpg/330px-%ED%95%98%EC%96%80%EB%A8%B8%EB%A6%AC_%EB%B0%B1%ED%98%84_3.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 14, 'EXO 세훈', 'EXO와 EXO-SC로 활동하는 래퍼, 배우, 댄서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Oh_Se-hun_at_Rimowa_Essential_Poly_Color_Collection_Launch_on_July_5%2C_2019.png/330px-Oh_Se-hun_at_Rimowa_Essential_Poly_Color_Collection_Launch_on_July_5%2C_2019.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 15, 'EXO 디오', 'EXO의 보컬이자 배우로 활동하는 도경수', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/D.O._at_the_press_conference_of_the_film_Underdog_in_January_2019.png/330px-D.O._at_the_press_conference_of_the_film_Underdog_in_January_2019.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 16, 'EXO 카이', 'EXO와 SuperM으로 활동한 퍼포먼스 강자', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Marie_Claire_Korea_Mterview_Kai.png/330px-Marie_Claire_Korea_Mterview_Kai.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 17, '세븐틴 민규', '세븐틴 힙합팀 소속의 래퍼이자 비주얼 멤버', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Mingyu_Bvlgari_240314.png/330px-Mingyu_Bvlgari_240314.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 18, '세븐틴 원우', '세븐틴 힙합팀 소속의 래퍼와 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Wonwoo_Follow_240330.jpg/330px-Wonwoo_Follow_240330.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 19, '세븐틴 호시', '세븐틴 퍼포먼스팀 리더로 알려진 댄서와 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/240415_Hoshi.jpg/330px-240415_Hoshi.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 20, '세븐틴 정한', '세븐틴 보컬팀 소속의 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Jeonghan_Follow_240330.jpg/330px-Jeonghan_Follow_240330.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 21, 'NCT 재현', 'NCT 127과 NCT 도재정으로 활동한 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/20231006_Jaehyun_%28NCT%29.jpg/330px-20231006_Jaehyun_%28NCT%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 22, 'NCT 태용', 'NCT의 리더로 활동한 래퍼, 싱어, 댄서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/20231006_Taeyong_%28NCT%29.jpg/330px-20231006_Taeyong_%28NCT%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 23, 'NCT 마크', 'NCT와 NCT 127, NCT Dream으로 활동한 래퍼', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/241025_Mark_Lee.jpg/330px-241025_Mark_Lee.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 24, 'NCT 도영', 'NCT 127과 NCT 도재정으로 활동한 보컬', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/20231006_Doyoung_%28NCT%29.jpg/330px-20231006_Doyoung_%28NCT%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 25, 'Stray Kids 현진', 'Stray Kids의 래퍼이자 퍼포먼스 멤버', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hyunjin_of_Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png/330px-Hyunjin_of_Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 26, 'Stray Kids 리노', 'Stray Kids의 보컬과 댄스를 맡는 멤버', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lee_Know_at_the_Incheon_Airport%2C_February_25%2C_2026_%284%29.png/330px-Lee_Know_at_the_Incheon_Airport%2C_February_25%2C_2026_%284%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 27, 'Stray Kids 방찬', 'Stray Kids의 리더이자 래퍼, 프로듀서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Bang_Chan_of_Stray_Kids%2C_February_23%2C_2026_%281%29.png/330px-Bang_Chan_of_Stray_Kids%2C_February_23%2C_2026_%281%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 28, 'TXT 연준', '투모로우바이투게더의 보컬, 래퍼, 댄서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Yeonjun_250625.jpg/330px-Yeonjun_250625.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 29, 'TXT 수빈', '투모로우바이투게더의 리더이자 싱어송라이터', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Choi_Soo-bin_at_a_Dior_event_in_2025_02.jpg/330px-Choi_Soo-bin_at_a_Dior_event_in_2025_02.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 30, 'ENHYPEN 성훈', 'ENHYPEN의 보컬이자 전 피겨 스케이터', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Sunghoon_of_Enhypen%2C_January_10%2C_2026_%281%29.png/330px-Sunghoon_of_Enhypen%2C_January_10%2C_2026_%281%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 31, 'ATEEZ 산', 'ATEEZ의 보컬과 퍼포먼스로 알려진 멤버', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Choi_San_%28Ateez%29_in_October_2024.png/330px-Choi_San_%28Ateez%29_in_October_2024.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'boy-idol'), 32, 'ATEEZ 홍중', 'ATEEZ의 리더이자 래퍼, 프로듀서', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Hongjoong_in_2024_%283%29_04.jpg/330px-Hongjoong_in_2024_%283%29_04.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 1, 'aespa 카리나', 'aespa의 리더로 활동하는 댄서, 래퍼, 보컬 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/KARINA%20-%20AESPA%20-%202025.01.28.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 2, 'aespa 지젤', 'aespa의 래퍼와 보컬을 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/GISELLE%20-%20AESPA%20-%202025.01.28.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 3, 'aespa 윈터', 'aespa의 보컬과 댄스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/WINTER%20-%20AESPA%20-%202025.01.28.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 4, 'aespa 닝닝', 'aespa의 보컬과 댄스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/NINGNING%20-%20AESPA%20-%202025.01.28.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 5, 'IVE 가을', 'IVE로 활동하는 퍼포먼스와 랩 중심의 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/MMA%202023%20IVE%20Gaeul%201.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 6, 'IVE 안유진', 'IVE의 리더로 활동하는 보컬과 퍼포먼스 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/IVE%20Yujin%20at%20Music%20Bank.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 7, 'IVE 레이', 'IVE의 래퍼와 보컬을 맡는 일본 출신 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ive%27s%20Rei%20in%202023.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 8, 'IVE 장원영', 'IVE의 보컬과 비주얼로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jang%20Wonyoung%20240513.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 9, 'IVE 리즈', 'IVE의 보컬을 맡는 멤버', 'ive-liz.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 10, 'IVE 이서', 'IVE의 막내 라인으로 활동하는 보컬 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/IVE%20Leeseo%20260215%20%281%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 11, 'NewJeans 민지', 'NewJeans로 데뷔한 보컬 중심의 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230905%20Minji%20%28NewJeans%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 12, 'NewJeans 하니', 'NewJeans의 보컬과 퍼포먼스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230905%20Hanni%20%28NewJeans%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 13, 'NewJeans 다니엘', 'NewJeans의 보컬과 밝은 무대로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Danielle%20%28NewJeans%29%20220813.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 14, 'NewJeans 해린', 'NewJeans의 보컬과 퍼포먼스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230905%20Haerin%20%28NewJeans%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 15, 'NewJeans 혜인', 'NewJeans의 막내 라인으로 활동하는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hyein%20of%20NewJeans%2C%20July%2026%2C%202024.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 16, 'LE SSERAFIM 사쿠라', 'LE SSERAFIM으로 활동하는 일본 출신 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230630%20Sakura%20%28LE%20SSERAFIM%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 17, 'LE SSERAFIM 김채원', 'LE SSERAFIM의 리더로 활동하는 보컬 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/220428%20Le%20Sserafim%20Kim%20Chae-won%20%281%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 18, 'LE SSERAFIM 허윤진', 'LE SSERAFIM의 보컬과 싱어송라이터 감각이 돋보이는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230630%20Huh%20Yun-jin%20%28LE%20SSERAFIM%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 19, 'LE SSERAFIM 카즈하', 'LE SSERAFIM의 퍼포먼스와 발레 기반 움직임으로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20230630%20Nakamura%20Kazuha%20%28LE%20SSERAFIM%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 20, 'LE SSERAFIM 홍은채', 'LE SSERAFIM의 막내 라인으로 활동하는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hong%20Eunchae%20of%20Le%20Sserafim%2C%20January%2010%2C%202025.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 21, 'NMIXX 릴리', 'NMIXX의 보컬 중심 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/NMIXX%27s%20Lily%202023.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 22, 'NMIXX 해원', 'NMIXX의 리더이자 보컬 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/221013%20Haewon%20%28NMIXX%29%20Airport%20Departure.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 23, 'NMIXX 설윤', 'NMIXX의 보컬과 비주얼로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/NMIXX%27s%20Sullyoon%202023.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 24, 'NMIXX 배이', 'NMIXX의 보컬과 퍼포먼스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/221013%20Bae%20%28NMIXX%29%20Airport%20Departure.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 25, 'NMIXX 지우', 'NMIXX의 랩, 보컬, 퍼포먼스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nmixx%27s%20Jiwoo%20in%20April%202023.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 26, 'NMIXX 규진', 'NMIXX의 막내 라인으로 활동하는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/NMIXX%20Kyujin%20251225%20%281%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 27, 'STAYC 수민', 'STAYC로 활동하는 보컬과 퍼포먼스 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/SUMIN%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 28, 'STAYC 시은', 'STAYC의 보컬로 활동하며 배우 경력도 있는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/SIEUN%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 29, 'STAYC 아이사', 'STAYC의 보컬과 음색으로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/ISA%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 30, 'STAYC 세은', 'STAYC의 보컬과 퍼포먼스를 맡는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/SEEUN%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 31, 'STAYC 윤', 'STAYC의 보컬과 무대 에너지로 알려진 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/YOON%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'girl-idol'), 32, 'STAYC 재이', 'STAYC의 막내 라인으로 활동하는 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/J%20%28STAYC%29%20220430.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 1, 'Taylor Swift', 'The Eras Tour와 재녹음 프로젝트로 2020년대 팝 신을 크게 흔든 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Taylor%20Swift%20at%20the%202023%20MTV%20Video%20Music%20Awards%20%282%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 2, 'Beyonce', 'Renaissance와 Cowboy Carter로 장르 경계를 확장한 보컬리스트이자 퍼포머', 'https://commons.wikimedia.org/wiki/Special:FilePath/Beyonc%C3%A9%20-%20Tottenham%20Hotspur%20Stadium%20-%201st%20June%202023%20%2889%20of%20118%29%20%2852945896886%29%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 3, 'Billie Eilish', '섬세한 보컬 톤과 미니멀한 프로덕션으로 독보적인 분위기를 만든 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Billie%20Eilish%20performing%20in%20Inglewood%20%28Dec%202024%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 4, 'Olivia Rodrigo', 'SOUR와 GUTS로 2020년대 팝 록 감성을 대표하게 된 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Olivia%20Rodrigo%202023%2002.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 5, 'Sabrina Carpenter', '재치 있는 팝 송라이팅과 무대 매력으로 빠르게 존재감을 키운 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/SABRINA%20CARPENTER.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 6, 'Ariana Grande', '섬세한 보컬 운용과 팝/R&B 감각을 함께 보여주는 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ariana%20Grande%20promoting%20Wicked%20%282024%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 7, 'Miley Cyrus', '허스키한 보컬과 록, 팝, 컨트리 감성을 넘나드는 퍼포머', 'https://commons.wikimedia.org/wiki/Special:FilePath/Miley%20Cyrus%20Grammy%20Awards%202024.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 8, 'Doja Cat', '랩과 팝을 오가며 독특한 비주얼과 훅 메이킹을 보여주는 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Doja%20Cat%20in%202024.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 9, 'SZA', 'SOS를 통해 얼터너티브 R&B의 결을 대중적으로 확장한 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/SZA%20in%202024.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 10, 'Selena Gomez', '차분한 팝 보컬과 배우 활동을 함께 이어가는 멀티 엔터테이너', 'https://commons.wikimedia.org/wiki/Special:FilePath/Selena%20Gomez%20at%20the%202024%20Golden%20Globes%20%282%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 11, 'Lana Del Rey', '시네마틱한 분위기와 독특한 서사 감각을 가진 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lana%20Del%20Rey%20%282024%29%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 12, 'Lady Gaga', '강한 콘셉트와 보컬 실력을 바탕으로 팝, 재즈, 영화 음악까지 넘나드는 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lady%20Gaga-65189.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 13, 'Chappell Roan', '극적인 팝 퍼포먼스와 퀴어 팝 감성으로 주목받은 신흥 스타', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chappell%20Roan%2008%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 14, 'Halsey', '개인적인 서사와 얼터너티브 팝 감성을 결합해 온 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Halsey%20%40%20Amazon%20Music%20Live%2010%2031%202024%20%2854228375097%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 15, 'Demi Lovato', '파워풀한 보컬과 팝 록 에너지를 함께 보여주는 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Demi%20Lovato%20in%202020.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-female-singer'), 16, 'Megan Thee Stallion', '강렬한 랩 플로우와 에너지 있는 퍼포먼스로 2020년대를 대표하는 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Megan%20Thee%20Stallion%20Adweek%202024%2003%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 1, 'Bruno Mars', '팝, R&B, 펑크 감각과 라이브 퍼포먼스로 꾸준히 사랑받는 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bruno%20Mars%20portrait.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 2, 'Post Malone', '힙합, 팝, 록, 컨트리를 넘나드는 멜로디 중심의 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Post%20Malone%20%2828734295876%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 3, 'Kendrick Lamar', '강한 서사와 랩 테크닉으로 2020년대에도 영향력을 이어간 힙합 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/KendrickSZASPurs230725-46%20-%2054683274355%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 4, 'Tyler, the Creator', '프로듀싱, 랩, 비주얼 콘셉트를 직접 구축하는 창작자형 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tyler%2C%20the%20Creator%20performing%20at%20Primavera%20Sound%2C%202022.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 5, 'Lil Nas X', '장르와 이미지를 과감하게 섞으며 팝 컬처에서 강한 존재감을 만든 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lil%20Nas%20X.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 6, 'Childish Gambino', '랩, 소울, 펑크를 오가며 음악과 영상 언어를 함께 다루는 멀티 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Childish%20Gambino%20a.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 7, 'Frank Ocean', '섬세한 보컬과 실험적인 R&B 감성으로 큰 영향력을 가진 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Frank%20Ocean%20%282013%29%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 8, 'Charlie Puth', '깔끔한 팝 멜로디와 프로듀싱 감각으로 알려진 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Charlie%20Puth.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 9, 'Khalid', '느긋한 보컬 톤과 청춘 감성의 R&B/팝 사운드로 사랑받는 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Khalid%20World%20Pride%20DC%2003%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 10, 'Giveon', '낮고 깊은 보컬 톤으로 현대 R&B의 클래식한 결을 살리는 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Photo%20of%20Giveon.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 11, 'Steve Lacy', '기타 기반의 얼터너티브 R&B와 독특한 프로덕션으로 주목받은 아티스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Steve%20Lacy%20%40%20Rialto%20Theatre.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 12, 'Jack Harlow', '부드러운 플로우와 대중적인 훅으로 존재감을 키운 래퍼', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jack%20Harlow%20%2851915306320%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 13, 'Zach Bryan', '담백한 가사와 거친 보컬 톤으로 컨트리와 포크 팬층을 넓힌 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zach%20Bryan%20Melbourne.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 14, 'Morgan Wallen', '컨트리 팝 사운드로 2020년대 미국 차트에서 강한 성과를 낸 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Morgan%20Wallen.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 15, 'Benson Boone', '감정적인 보컬과 드라마틱한 팝 발라드로 빠르게 주목받은 신예', 'https://commons.wikimedia.org/wiki/Special:FilePath/Benson%20Boone.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-us-male-singer'), 16, 'Teddy Swims', '소울풀한 보컬과 팝, R&B, 컨트리 감성을 함께 보여주는 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Teddy%20Swims%20Warner%20Records.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 1, '심상정', '정의당을 대표하는 진보 정치인으로 노동, 복지, 정치개혁 의제를 다뤄온 인물', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sim%20Sang-jung%20taking%20a%20commemorative%20photo%20with%20the%20Speaker%20of%20the%20National%20Assembly.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 2, '이정미', '정의당 대표와 국회의원을 지내며 노동, 젠더, 생태 의제를 중심으로 활동한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Jeong-mi%20taking%20a%20commemorative%20photo%20at%20the%20National%20Assembly.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 3, '권영국', '노동 인권 변호사 출신으로 진보정당 활동과 노동 의제를 이어온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kwon%20Yeong-guk.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 4, '용혜인', '기본소득당을 중심으로 기본소득, 재난지원, 청년 정치 의제를 제기해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yong%20Hyein.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 5, '장혜영', '정의당 국회의원으로 장애, 차별금지, 재정 정책 등 사회권 의제를 다뤄온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%EC%9E%A5%ED%98%9C%EC%98%81%20%EC%9D%98%EC%9B%90.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 6, '류호정', '청년 정치와 노동, 산업 정책 이슈를 중심으로 2020년대 국회에서 활동한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%EB%A5%98%ED%98%B8%EC%A0%95%20%EC%9D%98%EC%9B%90.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 7, '배진교', '정의당 원내대표 등을 맡으며 진보정당의 원내 활동을 이끌었던 정치인', 'https://www.assembly.go.kr/static/portal/img/openassm/A2V51235.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 8, '여영국', '정의당 대표와 국회의원을 지내며 노동자 정치와 지역 진보정치 의제를 다룬 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yeo%20Yeong-gug%20in%202021.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 9, '김재연', '진보당에서 활동하며 노동, 청년, 평화 의제를 중심으로 목소리를 내 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%9A%D0%B8%D0%BC%20%D0%94%D0%B6%D1%8D%20%D0%81%D0%BD.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 10, '강은미', '정의당 원내대표를 지내며 노동, 안전, 복지 의제를 다뤄온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%EA%B5%AD%ED%9A%8C%EC%9D%98%EC%9B%90%20%EA%B0%95%EC%9D%80%EB%AF%B8.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 11, '이재명', '더불어민주당 대표로 민생, 복지, 기본사회 등 진보·개혁 성향 의제를 제시해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Jae-myung%2C%202021%20%28cropped%201%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 12, '조국', '조국혁신당을 통해 검찰개혁과 권력기관 개혁 의제를 중심으로 활동한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cho%20Kuk%27s%20Portrait%20%282024.3%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 13, '추미애', '더불어민주당 계열에서 사법개혁과 권력기관 개혁 이슈로 주목받은 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Choo%20Mi-ae%20ministerial%20portrait.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 14, '박주민', '더불어민주당 국회의원으로 인권, 사법개혁, 사회 안전 의제를 다뤄온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Park%20Ju-Min%20%EB%B2%99%EC%BB%A41%20%ED%8A%B9%EA%B0%95%20%EB%8B%88%EA%B0%80%20%EA%B0%80%EB%9D%BC%20%EC%97%AC%EC%9D%98%EB%8F%84%2001.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 15, '김용민', '더불어민주당 국회의원으로 검찰개혁과 사법개혁 의제에 목소리를 내 온 정치인', 'https://www.assembly.go.kr/static/portal/img/openassm/new/e8f8918e741b4ae9b72377d8ec299645.png'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-progressive-politician'), 16, '한창민', '사회민주당을 중심으로 사회민주주의와 복지국가 의제를 제기해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%ED%95%9C%EC%B0%BD%EB%AF%BC%20%EC%9D%98%EC%9B%90.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 1, '윤석열', '국민의힘 계열에서 대통령을 지내며 2020년대 보수 정치의 중심에 선 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/South%20Korea%20President%20Yoon%20Suk%20Yeol%20portrait%20%28crop%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 2, '한동훈', '법무부 장관과 국민의힘 비상대책위원장을 지내며 보수 진영의 주요 인물로 부상한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Han%20Dong-hoon%27s%20Portrait%20%282025%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 3, '홍준표', '국민의힘 대선 경선 후보와 대구광역시장을 지내며 보수 진영에서 강한 존재감을 보여 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hong%20Jun-pyo%27s%20Portrait%20%282020%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 4, '오세훈', '서울특별시장으로 활동하며 도시 정책과 행정 경험을 바탕으로 보수 진영을 대표해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Oh%20Se-hoon%202023.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 5, '원희룡', '제주특별자치도지사와 국토교통부 장관을 지내며 보수 진영의 정책형 정치인으로 활동한 인물', 'https://commons.wikimedia.org/wiki/Special:FilePath/Minister%20of%20Land%2C%20Infrastructure%20and%20Transport%20WON%20Hee-ryong%2020231129.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 6, '안철수', '국민의힘에서 활동하며 중도·보수 연대와 과학기술 의제를 강조해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ahn%20Cheol-Soo%27s%20Portrait%20%282025%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 7, '이준석', '국민의힘 대표를 지내며 2020년대 보수 정치의 세대교체와 정당 혁신 이슈를 이끈 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Jun-seok.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 8, '나경원', '국민의힘 계열에서 원내대표 등을 지내며 보수 정당의 주요 인물로 활동해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Na%20Kyung-won%27s%20Portrait%20%282016.12%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 9, '김기현', '국민의힘 대표와 울산광역시장을 지내며 보수 정당 운영과 지역 행정을 경험한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/%EA%B9%80%EA%B8%B0%ED%98%84%20%EC%A0%84%20%EC%9A%B8%EC%82%B0%EC%8B%9C%EC%9E%A5.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 10, '권성동', '국민의힘 원내대표 등을 맡으며 보수 진영의 원내 전략과 정당 운영에 참여해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kweon%20Seong-dong%27s%20Portrait%20%282025.1%29.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 11, '장제원', '국민의힘 국회의원으로 활동하며 2020년대 보수 정권과 정당 내 주요 이슈에서 주목받은 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chang%20Je-won%202018-11-22.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 12, '유승민', '경제 정책과 개혁 보수 노선을 강조하며 보수 진영의 대선 주자로 활동해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yoo%20Seong-min%20in%20Gangneung%20%28Cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 13, '김태호', '경상남도지사와 국회의원을 지내며 보수 진영에서 지역 행정과 중앙 정치를 경험한 정치인', 'https://s3.ap-northeast-2.amazonaws.com/wwk.file/production/category/identity/2023/10/06/1696519835745-%EA%B9%80%ED%83%9C%ED%98%B8.webp'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 14, '조경태', '국민의힘 국회의원으로 활동하며 보수 진영의 중진 정치인으로 자리해 온 인물', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cho%20Kyoung-tae%2020250203.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 15, '배현진', '국민의힘 국회의원으로 2020년대 보수 정당의 대변과 의정 활동에 참여해 온 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bae%20Hyun-jin%2C%20June%201%2C%202020%2C%20news%26newsTV%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-conservative-politician'), 16, '김은혜', '국민의힘 국회의원과 대통령실 홍보수석을 지내며 보수 진영에서 메시지와 선거 이슈로 활동한 정치인', 'https://commons.wikimedia.org/wiki/Special:FilePath/2017%2002%EC%9B%94%2022%EC%9D%BC%20MBN%20Y%20Forum%202017%20%2812%29%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 1, '양현종', 'KIA 타이거즈를 대표하는 좌완 에이스로 2020년대에도 꾸준한 선발 투수 존재감을 보여준 선수', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/%EC%96%91%ED%98%84%EC%A2%85_%28KIA_%ED%83%80%EC%9D%B4%EA%B1%B0%EC%A6%88%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 2, '최정', 'SSG 랜더스의 장타 중심 타자로 KBO 통산 홈런 기록 경쟁을 이끈 대표적인 3루수', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Jeong_Choi_on_March_2%2C_2013.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 3, '이정후', '정교한 타격과 스타성을 앞세워 2020년대 초반 KBO를 대표한 외야수', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Kiwoom_Heroes_Lee_Jeong-Hoo_%282019%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 4, '강백호', 'KT 위즈의 중심 타자로 강한 타격 재능과 장타력을 보여준 2020년대 KBO 스타', 'https://upload.wikimedia.org/wikipedia/commons/5/58/Kang_Baek-Ho_2019_Premier_12.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 5, '양의지', '공수에서 영향력이 큰 포수로 두산과 NC에서 우승 경쟁의 중심에 섰던 선수', 'https://upload.wikimedia.org/wikipedia/commons/2/25/151208._2015_KBO_%EA%B3%A8%EB%93%A0_%EA%B8%80%EB%9F%AC%EB%B8%8C_%EC%8B%9C%EC%83%81%EC%8B%9D._62.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 6, '구자욱', '삼성 라이온즈의 중심 외야수로 정교한 타격과 장타력을 함께 보여준 선수', 'https://upload.wikimedia.org/wikipedia/commons/7/74/2017_09_01_%EC%82%BC%EC%84%B1_vs_SK_%EA%B5%BF%EB%B0%94%EC%9D%B4_%EB%9D%BC%EC%9D%B4%EC%98%A8%ED%82%B9_1_%284%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 7, '나성범', '강한 어깨와 장타력을 갖춘 외야수로 NC와 KIA에서 중심 타선을 맡은 선수', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/%EB%82%98%EC%84%B1%EB%B2%94_%EC%84%A0%EC%88%98.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 8, '손아섭', '꾸준한 안타 생산력으로 KBO 리그를 대표하는 교타자 계보를 이어온 외야수', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Son_Ah-Seop2023.webp'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 9, '김재환', '두산 베어스의 장타력 있는 좌타 거포로 중심 타선에서 활약한 선수', 'https://upload.wikimedia.org/wikipedia/commons/5/52/Kim_Jae-hwan_%EA%B9%80%EC%9E%AC%ED%99%98_2016_%EA%B3%A8%EB%93%A0%EA%B8%80%EB%9F%AC%EB%B8%8C.png'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 10, '오지환', 'LG 트윈스의 주전 유격수로 안정적인 수비와 팀 리더십을 보여준 선수', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/%EC%98%A4%EC%A7%80%ED%99%98LG%EC%A3%BC%EC%9E%A5.png'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 11, '박민우', 'NC 다이노스의 내야 핵심 자원으로 빠른 발과 컨택 능력을 갖춘 선수', 'https://upload.wikimedia.org/wikipedia/commons/2/29/151208._2015_KBO_%EA%B3%A8%EB%93%A0_%EA%B8%80%EB%9F%AC%EB%B8%8C_%EC%8B%9C%EC%83%81%EC%8B%9D._48.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 12, '고영표', 'KT 위즈의 제구형 선발 투수로 안정적인 이닝 소화 능력을 보여준 선수', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/%EA%B3%A0%EC%98%81%ED%91%9C_%EC%95%BC%EA%B5%AC_%EC%84%A0%EC%88%98.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 13, '원태인', '삼성 라이온즈의 젊은 우완 선발 투수로 국가대표와 리그에서 성장세를 보여준 선수', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Won_Tae-in_%28ZGbHvfTK0V4%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 14, '문동주', '한화 이글스의 강속구 유망주로 2020년대 KBO를 대표할 젊은 투수로 주목받은 선수', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Moon_Dong-ju_2023.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 15, '홍창기', 'LG 트윈스의 출루 능력 좋은 외야수로 팀 공격의 연결고리 역할을 맡은 선수', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/%ED%99%8D%EC%B0%BD%EA%B8%B0_%EC%84%A0%EC%88%98.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-kbo-baseball-player'), 16, '김혜성', '키움 히어로즈의 빠른 발과 수비력을 갖춘 내야수로 2020년대 리그에서 꾸준히 활약한 선수', 'https://upload.wikimedia.org/wikipedia/commons/1/11/%EA%B9%80%ED%98%9C%EC%84%B1_%EC%84%A0%EC%88%98.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 1, '오타니 쇼헤이', '투타 겸업과 MVP급 활약으로 2020년대 메이저리그를 대표하는 슈퍼스타', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Dodgers_at_Nationals_%2853677192000%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 2, '애런 저지', '압도적인 장타력과 홈런 생산력으로 뉴욕 양키스 타선을 이끄는 거포', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Aaron_Judge_posing_with_Donald_Trump_2025-09-11_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 3, '마이크 트라웃', '공수주를 겸비한 메이저리그 최고 외야수 계보의 중심에 있는 선수', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Mike_Trout_%2852252097714%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 4, '무키 베츠', '정교한 타격과 수비, 주루를 모두 갖춘 2020년대 다재다능한 스타', 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Dodgers_at_Nationals_%2853676957188%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 5, '브라이스 하퍼', '강한 스타성과 클러치 능력으로 필라델피아 타선을 상징하는 강타자', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Bryce_Harper_Stare_Down_Pregame_from_Nationals_vs._Phillies_at_Nationals_Park%2C_May_13th%2C_2021_%28All-Pro_Reels_Photography%29_%2851188354283%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 6, '프레디 프리먼', '꾸준한 타격과 리더십으로 2020년대 정상급 1루수로 활약한 선수', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Freddie_Freeman_-_Dodgers_vs_Nationals_4-23-2024.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 7, '클레이튼 커쇼', '세대를 대표하는 좌완 에이스로 큰 경기와 정규시즌에서 존재감을 이어온 투수', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Clayton_Kershaw_on_July_23%2C_2015_%282%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 8, '후안 소토', '뛰어난 선구안과 장타력을 앞세워 젊은 나이에 리그 최정상급 타자로 올라선 선수', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Mets_Spring_Training%2C_March_23%2C_2025_%28Leo_Altes%29_-_00010_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 9, '게릿 콜', '강력한 구위와 탈삼진 능력으로 2020년대 메이저리그를 대표한 선발 투수', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Gerrit_Cole_%2853947688783%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 10, '류현진', '정교한 제구와 완급 조절로 한국 야구 팬들에게 오래 사랑받은 좌완 투수', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Ryu_Hyun-jin_2025.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 11, '김하성', '내야 전 포지션을 소화하는 수비력과 주루, 장타를 갖춘 한국인 메이저리거', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Ha-seong_Kim-25.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 12, '이정후', 'KBO 최고 타자에서 메이저리그로 도전한 정교한 컨택형 외야수', 'https://upload.wikimedia.org/wikipedia/commons/2/23/JHLee.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 13, '야마모토 요시노부', '일본 프로야구를 평정한 뒤 메이저리그에서도 주목받은 정상급 선발 투수', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Yoshinobu_Yamamoto_in_2024_%2853676737736%29_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 14, '로날드 아쿠냐 주니어', '파워와 스피드를 동시에 갖춘 애틀랜타의 프랜차이즈급 외야수', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Ronald_Acuna_Jr._HR_from_Nationals_vs._Braves_at_Nationals_Park%2C_April_6th%2C_2021_%28All-Pro_Reels_Photography%29_%2851102624580%29.png'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 15, '매니 마차도', '강한 타구 생산력과 3루 수비로 2020년대 샌디에이고를 대표한 스타', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Manny_Machado_8.27.21_%28cropped%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '2020-mlb-baseball-player'), 16, '블라디미르 게레로 주니어', '강력한 스윙과 장타력으로 토론토 타선의 중심을 맡은 1루수', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Vladimir_guerrero_jr.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 1, '김건모', '1992년 데뷔 후 1990년대 한국 대중음악을 대표한 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim_Kun-Mo.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 2, '신승훈', '1990년 데뷔한 발라드 가수로 ''발라드의 황제''라 불린 대표 보컬', 'https://commons.wikimedia.org/wiki/Special:FilePath/Shin_Seung-hun_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 3, '서태지', '서태지와 아이들로 1990년대 한국 대중음악의 흐름을 바꾼 뮤지션', 'https://commons.wikimedia.org/wiki/Special:FilePath/Seo_Taiji_on_October_20%2C_2014_%282%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 4, '이승환', '1989년 데뷔 후 1990년대 발라드와 록을 넘나든 라이브형 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/LSH_-_2019_No_Enemy_Legend.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 5, '조성모', '1998년 데뷔해 1990년대 말 발라드 열풍을 이끈 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jo_Sungmo_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 6, '윤종신', '015B 객원 보컬과 솔로 활동으로 1990년대부터 사랑받은 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yoon_Jong-shin_at_%22Persona%22_press_conference%2C_27_March_2019.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 7, '김종서', '시나위와 솔로 활동을 거친 1990년대 대표 록 보컬', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim_Jong-seo_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 8, '임창정', '1990년대 후반 가수와 배우 활동을 함께 펼친 발라드 보컬', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lim_Chang-Jung_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 9, '박진영', '1994년 솔로 데뷔 후 댄스, R&B, 프로듀싱으로 영향력을 넓힌 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Park_Jin-young_%28Founder_of_JYP_Entertainment%29_in_February_2011_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 10, '현진영', '1990년 데뷔해 한국 힙합과 댄스 음악의 초기 흐름을 연 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hyunjinyoung2021.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 11, '김원준', '1992년 데뷔해 1990년대 댄스팝과 청춘 스타 이미지를 대표한 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim_Won_Joon_from_acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 12, '이현우', '1990년대 감성적인 팝 발라드로 활동한 가수 겸 배우', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee_Hyun-Woo_%28singer%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 13, '이승철', '부활 보컬과 솔로 활동을 거쳐 1990년대에도 사랑받은 록 발라드 보컬', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Seung-cheol%20from%20acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 14, '김민종', '1990년대 배우와 가수 활동을 병행하며 큰 인기를 얻은 발라드 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim_Min-jong_2025.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 15, '이적', '패닉과 카니발, 솔로 활동으로 1990년대 감성 음악을 대표한 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee_Juck_20161109_02.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-male-singer'), 16, '김광석', '1990년대 초중반 깊은 포크 감성으로 사랑받은 싱어송라이터', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim_Kwang-seok_performing_live_in_1992.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 1, '엄정화', '1993년 가수 데뷔 후 1990년대 댄스팝과 무대를 대표한 솔로 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/2009Uhm%20Jung-hwa%20%282%29%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 2, '이소라', '1995년 솔로 데뷔 후 깊은 감성의 보컬로 1990년대 발라드를 대표한 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/180617%20Lee%20So-ra%20at%20Pilsner%20Festival.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 3, '박미경', '1990년대 파워풀한 보컬과 댄스곡으로 사랑받은 여성 솔로 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Park%20Mi-Kyung.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 4, '양파', '1996년 데뷔해 1990년대 후반 발라드 신예로 큰 인기를 얻은 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yangpa%20at%20the%202007%20Cyworld%20Digital%20Music%20Awards.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 5, '장혜진', '1990년대 감성 발라드와 안정적인 보컬로 사랑받은 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jang%20Hye-Jin.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 6, '백지영', '1999년 데뷔해 댄스와 발라드 모두에서 존재감을 보인 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Baek%20Ji-Young%20in%202009.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 7, 'S.E.S. 바다', '1997년 S.E.S.로 데뷔해 1990년대 1세대 걸그룹 보컬을 대표한 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/150118%20%EB%B0%94%EB%8B%A4%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 8, 'Fin.K.L 이효리', '1998년 Fin.K.L로 데뷔해 1990년대 후반 걸그룹 인기를 이끈 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Hyori%2C%202012%20%28cropped%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 9, 'Fin.K.L 옥주현', '1998년 Fin.K.L 메인보컬로 데뷔한 1990년대 대표 걸그룹 멤버', 'https://commons.wikimedia.org/wiki/Special:FilePath/20170613%E2%80%94Ock%20Joo-hyun%20%EC%98%A5%EC%A3%BC%ED%98%84%20and%20Lim%20Seul-ong%20%EC%9E%84%EC%8A%AC%EC%98%B9%2C%20%22Mata%20Hari%22%20photo%20shoot%2C%20scene%20PLAYBILL%20screenshot%20%2800m51s%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 10, '박정현', '1998년 한국 데뷔 후 R&B와 발라드 보컬로 주목받은 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Park%20Jung-hyun.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 11, '김현정', '1998년 데뷔해 시원한 고음과 댄스곡으로 1990년대 후반을 대표한 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim%20Hyun-Jung%20%28singer%29%20from%20acrofan.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 12, '김완선', '1980년대 데뷔 후 1990년대에도 퍼포먼스형 여성 솔로의 상징으로 활동한 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kim%20Wan-Sun.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 13, '이은미', '1989년 데뷔 후 1990년대 라이브와 발라드 감성으로 사랑받은 보컬리스트', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Eun-Mi.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 14, '신효범', '1990년대 소울풀한 창법과 탄탄한 가창력으로 알려진 여성 보컬', 'https://commons.wikimedia.org/wiki/Special:FilePath/Shin%20Hyo-Bum.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 15, '소향', '1996년 데뷔해 폭넓은 음역과 파워풀한 보컬로 알려진 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sohyang%20in%20June%202022.png?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = '1990-female-singer'), 16, '박지윤', '1997년 가수 데뷔 후 1990년대 말부터 주목받은 여성 솔로 가수', 'https://commons.wikimedia.org/wiki/Special:FilePath/Park%20Ji-yoon%20%28close-up%29.jpg?width=480'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 1, '엄마', '아리네 가족의 중심이 되는 활기차고 개성 강한 엄마', 'https://static.wikia.nocookie.net/atashinchi/images/a/ae/OkaasanMangaProfile.png/revision/latest?cb=20230218153724'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 2, '아빠', '말수는 적지만 자기만의 규칙과 가족애가 있는 아빠', 'https://static.wikia.nocookie.net/atashinchi/images/6/63/Otou-san_Tachibana.png/revision/latest?cb=20240607001232'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 3, '오아리', '일상 속 고민과 상상을 솔직하게 보여주는 딸', 'https://static.wikia.nocookie.net/atashinchi/images/0/07/MikanMangaProfilev2.png/revision/latest?cb=20230218144710'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 4, '오동동', '차분하고 섬세한 성격이 돋보이는 아리의 남동생', 'https://static.wikia.nocookie.net/atashinchi/images/4/4d/YuzuMangaProfile.png/revision/latest?cb=20230219153012'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 5, '남선남', '아리의 가장 가까운 친구로 차분하고 현실적인 조언을 자주 건네는 인물', 'https://static.wikia.nocookie.net/atashinchi/images/b/b7/ShimizuAnime.png/revision/latest?cb=20231024193850'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 6, '신여울', '동동이 반 친구로 독특한 분위기와 말투가 인상적인 인물', 'https://static.wikia.nocookie.net/atashinchi/images/2/27/Yamashita2002Profile.png/revision/latest?cb=20240805125908'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 7, '박철연', '아리의 마음을 흔드는 학교 친구이자 풋풋한 감정선의 중심 인물', 'https://static.wikia.nocookie.net/atashinchi/images/0/07/MikanMangaProfilev2.png/revision/latest?cb=20230218144710'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 8, '이원중', '아리와 같은 학교의 친구로 여러 일상 에피소드에 등장하는 인물', 'https://static.wikia.nocookie.net/atashinchi/images/b/b7/ShimizuAnime.png/revision/latest?cb=20231024193850'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 9, '김한돌', '동동이의 학교생활을 함께 채우는 친구 캐릭터', 'https://static.wikia.nocookie.net/atashinchi/images/4/4d/YuzuMangaProfile.png/revision/latest?cb=20230219153012'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 10, '박정식', '동동이 반 친구로 장난기 있는 학교생활 에피소드에 등장하는 인물', 'https://i.ytimg.com/vi/H4cjWIC4Y2Q/hqdefault.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 11, '승민 엄마', '엄마의 주변 인물로 동네와 학부모 모임 에피소드에 등장', 'https://static.wikia.nocookie.net/atashinchi/images/1/1f/MizushimaAnimeProfile.png/revision/latest?cb=20250607170239'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 12, '진주 엄마', '엄마의 친구로 수다와 생활 에피소드에 자주 엮이는 인물', 'https://static.wikia.nocookie.net/atashinchi/images/1/1f/MizushimaAnimeProfile.png/revision/latest?cb=20250607170239'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 13, '단비 엄마', '엄마의 주변 관계를 보여주는 동네 친구 캐릭터', 'https://static.wikia.nocookie.net/atashinchi/images/1/1f/RioMamaAnime.png/revision/latest?cb=20231014110536'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 14, '보라 엄마', '엄마와 함께 생활감 있는 에피소드를 만드는 이웃 캐릭터', 'https://static.wikia.nocookie.net/atashinchi/images/1/1f/MizushimaAnimeProfile.png/revision/latest?cb=20250607170239'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 15, '은별', '동동이를 좋아하는 팬클럽 쪽 인물로 밝고 들뜬 에피소드를 만든다', 'https://static.wikia.nocookie.net/atashinchi/images/2/27/Yamashita2002Profile.png/revision/latest?cb=20240805125908'),
  ((SELECT id FROM favorite_topics WHERE value = 'atashinchi-character'), 16, '송이', '동동이 팬클럽 쪽 인물로 은별과 함께 동동이 이야기에 자주 엮인다', 'https://static.wikia.nocookie.net/atashinchi/images/e/e1/KawashimaAnimeProfile.png/revision/latest?cb=20240704200750'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 1, '이영애', '워킹맘이 된 시리즈의 중심 인물로 현실적인 직장과 가족 이야기를 이끈다', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615040.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 2, '이승준', '영애의 남편으로 육아와 직장 사이에서 고군분투하는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615041.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 3, '이규한', '영애 주변에서 능청스러운 매력과 엉뚱한 상황을 만드는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615042.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 4, '연제형', '젊고 훈훈한 매력으로 낙원사 주변 관계에 활기를 더하는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615043.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 5, '정보석', '낙원사에 새 긴장감을 불어넣는 사장 캐릭터', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615044.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 6, '라미란', '낙원사의 강렬한 존재감으로 직장 에피소드의 웃음을 책임지는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615045.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 7, '윤서현', '낙원사의 원년 멤버로 직장인의 애환과 생활감을 보여주는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615046.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 8, '정지순', '능청스러운 말투와 얄미운 행동으로 오래 사랑받은 낙원사 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615047.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 9, '김혁규', '영애 가족과 연결된 익숙한 인물로 현실적인 가족 에피소드를 만든다', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615048.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 10, '나수아', '새로운 낙원사 관계와 젊은 에너지를 더하는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615049.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 11, '이귀현', '영애의 가족 이야기를 오래 지켜온 아버지 캐릭터', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615050.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 12, '김정하', '영애 가족의 중심을 잡는 어머니 캐릭터', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615051.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 13, '이영채', '영애의 동생으로 가족 관계와 일상 에피소드에 활기를 더한다', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120182283/kr/B120182283_character_1669718615052.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 14, '김산호', '시즌6부터 합류해 영애와 오래 얽힌 과거 러브라인의 핵심 인물', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/190425_%EA%B9%80%EC%82%B0%ED%98%B8_%282%29.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 15, '한기웅', '시즌13에서 영애에게 적극적으로 다가오며 삼각 로맨스를 만든 낙원사 사원', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120131528/kr/B120131528_character_1669718612561.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 16, '스잘', '낙원 인쇄소의 오래된 남성 멤버로 사무실 케미를 더하는 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120176521/kr/B120176521_character_1669718614272.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 17, '조덕제', '시즌14와 시즌15에서 낙원사 쪽 갈등과 웃음을 만든 사장 캐릭터', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120169309/kr/B120169309_character_1669718613852.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 18, '조동혁', '시즌15에서 영애와 승준 사이에 새로운 긴장감을 만든 남자 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120169309/kr/B120169309_character_1669718613858.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 19, '정수환', '시즌15 해물포차 라인에서 조동혁과 함께 등장한 젊은 남성 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120169309/kr/B120169309_character_1669718613859.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 20, '이영민', '영애의 남동생으로 가족 에피소드에 등장하는 남성 가족 캐릭터', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120131528/kr/B120131528_character_1669718612570.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 21, '최원준', '시즌1부터 영애의 연하남 러브라인으로 등장한 초기 남자 주인공', 'https://dimg.donga.com/wps/NEWS/IMAGE/2008/08/28/7081201.1.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 22, '박선호', '시즌14에서 조현영과의 로맨스 라인으로 젊은 남성 캐릭터 축을 만든 인물', 'https://upload.wikimedia.org/wikipedia/commons/6/60/190102_%EB%B0%95%EC%84%A0%ED%98%B8_MBN_%27%EC%B5%9C%EA%B3%A0%EC%9D%98_%EC%B9%98%ED%82%A8%27_%EC%A0%9C%EC%9E%91%EB%B0%9C%ED%91%9C%ED%9A%8C_%EC%A7%81%EC%BA%A0_01.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 23, '박두식', '시즌14에서 조현영과 얽히며 낙원사 주변 젊은 남성 캐릭터로 등장한 인물', 'https://upload.wikimedia.org/wikipedia/commons/2/23/180212_%EB%B0%95%EB%91%90%EC%8B%9D.png'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 24, '김선아', '시즌13 낙원사 경리로 합류해 허세와 철없는 매력으로 사무실 에피소드를 만든 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120131528/kr/B120131528_character_1669718612562.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 25, '조현영', '시즌14에서 박선호와 박두식을 사이에 둔 젊은 로맨스 라인을 만든 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120144372/kr/B120144372_character_1669718613187.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 26, '이수민', '시즌15와 시즌16 디자인팀 사원으로 등장해 낙원사 젊은 직원 라인을 넓힌 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120169309/kr/B120169309_character_1669718613856.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 27, '손수현', '시즌16에서 승준, 규한과 연결된 새 여성 캐릭터로 관계 구도에 변화를 준 인물', 'https://poc-cf-image.cjenm.com/public/pcms/character/B120176521/kr/B120176521_character_1669718614275.png?v=1716957266'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 28, '강예빈', '시즌11과 시즌12에서 영애와 얽힌 예빈으로 등장해 갈등과 웃음을 만든 인물', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Kang_Ye-bin_%28%EA%B0%95%EC%98%88%EB%B9%88%29_from_acrofan.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'rude-miss-young-ae'), 29, '강소라', '시즌7과 시즌8에서 영민의 아내 소라로 등장했고 시즌12에도 특별 출연한 인물', 'https://upload.wikimedia.org/wikipedia/commons/3/31/Kang_So-ra_in_July_2024.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 1, '뽀로로', '호기심 많고 장난기 넘치는 꼬마 펭귄', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PororoCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 2, '크롱', '뽀로로와 함께 지내는 귀여운 아기 공룡', 'https://pororo.fandom.com/wiki/Special:Redirect/file/CrongCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 3, '루피', '상냥하고 섬세한 성격의 비버 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/LoopyCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 4, '에디', '발명과 실험을 좋아하는 영리한 여우', 'https://pororo.fandom.com/wiki/Special:Redirect/file/EddyCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 5, '포비', '든든하고 마음씨 좋은 북극곰 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PobyCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 6, '패티', '밝고 활발하며 운동을 좋아하는 펭귄 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PettyCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 7, '해리', '노래 부르기를 좋아하는 작은 벌새', 'https://pororo.fandom.com/wiki/Special:Redirect/file/HarryCurrentOutfit.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 8, '로디', '에디가 만든 로봇 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/RodyScreenShot.jpeg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 9, '삐삐', '작고 발랄한 장난꾸러기 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PipiScreenshot.jpeg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 10, '뽀뽀', '삐삐와 함께 다니는 다정한 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/PopoScreenshot.jpeg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 11, '상어', '바닷속 분위기를 더하는 강렬한 캐릭터', 'https://pororo.fandom.com/wiki/Special:Redirect/file/Shark_Pororo.jpg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 12, '통통이', '마법을 쓰는 주황색 드래곤 친구', 'https://pororo.fandom.com/wiki/Special:Redirect/file/TongTong.jpeg'),
  ((SELECT id FROM favorite_topics WHERE value = 'pororo-character'), 13, '벽시계', '친구들의 일상 속 시간을 알려주는 캐릭터', 'https://pororo.fandom.com/wiki/Special:Redirect/file/Pororo_Wall_Clock.jpg')
ON CONFLICT(topic_id, source_card_id) DO UPDATE SET
  name = excluded.name,
  description = excluded.description,
  image = excluded.image,
  updated_at = CURRENT_TIMESTAMP;
-- END pick-your-favorite seed data

CREATE TABLE IF NOT EXISTS quiz_topics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_quiz_topics_title
ON quiz_topics(title);

CREATE TABLE IF NOT EXISTS quiz_words (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id INTEGER NOT NULL,
  abbreviation TEXT NOT NULL,
  full_name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (topic_id) REFERENCES quiz_topics(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_quiz_words_topic_abbreviation
ON quiz_words(topic_id, abbreviation);

CREATE INDEX IF NOT EXISTS idx_quiz_words_topic_id
ON quiz_words(topic_id);
